ALTER TABLE item MODIFY code VARCHAR(185) ;
  CREATE INDEX CODE_INDEX ON item(code);
  ALTER TABLE item MODIFY name VARCHAR(185) ;
  CREATE INDEX NAME_INDEX ON item(name);
  ALTER TABLE item MODIFY DISPLAYNAME VARCHAR(185) ;
  CREATE INDEX DISPLAYNAME_INDEX ON item(DISPLAYNAME);
  CREATE INDEX ORDERNO_INDEX ON item(ORDERNO);
  CREATE INDEX RETIRED_INDEX ON item(RETIRED);
  CREATE INDEX CREATEDAT_INDEX ON item(CREATEDAT);
  CREATE INDEX EDITEDDAT_INDEX ON item(EDITEDAT);
  ALTER TABLE item MODIFY ITEMTYPE VARCHAR(185) ;
  CREATE INDEX ITEMTYPE_INDEX ON item(ITEMTYPE);
  ALTER TABLE item MODIFY DATATYPE VARCHAR(185) ;
  CREATE INDEX DATATYPE_INDEX ON item(DATATYPE);
 
 
  ALTER TABLE component MODIFY DTYPE VARCHAR(185) ;
  CREATE INDEX DTYPE_INDEX ON component(DTYPE);
 
  ALTER TABLE component MODIFY name VARCHAR(185) ;
  CREATE INDEX NAME_INDEX ON component(name);
 
 
 
  CREATE INDEX RETIRED_INDEX ON component(RETIRED);
 
  CREATE INDEX INSTITUTION_ID_INDEX ON component(INSTITUTION_ID);
  CREATE INDEX ORDERNO_INDEX ON component(ORDERNO);
 
  ALTER TABLE component MODIFY COMPONENTSEX VARCHAR(185) ;
  CREATE INDEX COMPONENTSEX_INDEX ON component(COMPONENTSEX);
 
  CREATE INDEX COMPLETEDAT_INDEX ON component(COMPLETEDAT);
  CREATE INDEX COMPLETED_INDEX ON component(COMPLETED);
  CREATE INDEX COMPLETEDBY_ID_INDEX ON component(COMPLETEDBY_ID);
  CREATE INDEX ITEM_ID_INDEX ON component(ITEM_ID);
 
  ALTER TABLE component MODIFY CODE VARCHAR(185) ;
  CREATE INDEX CODE_INDEX ON component(CODE);
 
  CREATE INDEX CREATEDAT_INDEX ON component(CREATEDAT);
 
  ALTER TABLE client MODIFY PHN VARCHAR(50) ;
  CREATE INDEX PHN_INDEX ON client(PHN);
 
  CREATE INDEX CREATEINSTITUTION_ID_INDEX ON client(CREATEINSTITUTION_ID);
  CREATE INDEX RETIRED_INDEX ON client(RETIRED);
 
  CREATE INDEX COMPLETED_INDEX ON encounter(COMPLETED);
  CREATE INDEX COMPLETEDAT_INDEX ON encounter(COMPLETEDAT);
  CREATE INDEX CREATEAT_INDEX ON encounter(CREATEAT);