-- ALTER TABLE area MODIFY CODE VARCHAR(185) ;
-- CREATE INDEX CODE_INDEX ON area(CODE);
--   ALTER TABLE area MODIFY NAME VARCHAR(185) ;
-- CREATE INDEX NAME_INDEX ON area(NAME);

-- CREATE INDEX RETIRED_INDEX ON area(RETIRED);

-- ALTER TABLE area MODIFY TYPE VARCHAR(185) ;
-- CREATE INDEX TYPE_INDEX ON area(TYPE);

-- ALTER TABLE institution MODIFY CODE VARCHAR(185) ;
-- CREATE INDEX CODE_INDEX ON institution(CODE);

-- ALTER TABLE institution MODIFY INSTITUTIONTYPE VARCHAR(185) ;
-- CREATE INDEX INSTITUTIONTYPE_INDEX ON institution(INSTITUTIONTYPE);


-- CREATE INDEX LASTHIN_INDEX ON institution(LASTHIN);

-- ALTER TABLE institution MODIFY NAME VARCHAR(185) ;
-- CREATE INDEX NAME_INDEX ON institution(NAME);

-- CREATE INDEX RETIRED_INDEX ON institution(RETIRED);

-- CREATE INDEX PMCI_INDEX ON institution(PMCI);

CREATE INDEX POIINSTITUTION_ID_INDEX ON institution(POIINSTITUTION_ID);
CREATE INDEX MOHAREA_ID_INDEX ON institution(MOHAREA_ID);


